[contract]
starknetid = "0x0783a9097b26eae0586373b2ce0ed3529ddc44069d1e0fbc4f66d42b69d6850d"
naming = "0x3bab268e932d2cecd1946f100ae67ce3dff9fd234119ea2f6da57d16d29fce"
pricing = "0x2ad9830baa7d300a50329f258bac290f3895a596c087a9c091093f3d11ee277"
renewal = "0x07879a0d106d8e48751be4c01373e27bee0613afb0e5b8bbc569610fc0514a3a"
erc20 = "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"

[database]
name = "starknetid"
connection_string = ""
metadata_name = "goerli"
connection_string_metadata = ""

[account]
private_key = "0x123"
address = "0x123"

[renewals]
delay = 86400 # 24 hours

[indexer_server]
port = [8005, 8007, 8008]
server_url = "http://0.0.0.0"

[watchtower]
endpoint = "https://api.watchtower.starknet.id/service/add_message"
app_id = "XXXXXXXXXXXXXXXXX"
token = "XXXXXXXXXXXXXXXXX"
[watchtower.types]
info = "goerli/info"
warning = "goerli/warning"
severe = "goerli/severe"

[rpc]
rpc_url = "https://starknet-goerli.g.alchemy.com/v2/xxxxxxx"
