version: '3'

services:

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: auto_renew
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 0.0.0.0:27017:27017

  indexer:
    container_name: indexer
    build: 
      context: .
      dockerfile: ./indexer/Dockerfile
    command: ./target/release/indexer
    restart: always
    links:
      - mongo

  bot:
    container_name: bot
    build: 
      context: .
      dockerfile: ./bot/Dockerfile
    command: ./target/release/bot
    restart: "no"
    links:
      - mongo
