version: '3'
services:
  devnet:
    image: shardlabs/starknet-devnet:0.6.2
    command:
    - "--host=0.0.0.0"
    - "--port=5050"
    - "--disable-rpc-request-validation"
    - "--seed=0"
    - "--timeout=5000"
    ports:
    - 5050:5050

  apibara:
    image: quay.io/apibara/starknet:1.0.3
    ports:
    - 7171:7171
    # apibara requires devnet to be available, which is not always the case
    # when the containers first launch
    # so restart it until it's working
    depends_on:
    - devnet
    restart: always
    command:
    - "start"
    - "--data=/data"
    - "--rpc=http://devnet:5050/rpc"
    - "--wait-for-rpc"
    environment:
    - OTEL_SDK_DISABLED=true # disable tracing/metrics
    volumes:
    - apibara-data:/data

volumes:
  apibara-data: